import Header from "@/components/Header";

export default function Reference() {
  const keywords = [
    { name: "abstract", description: "A non-access modifier used for classes and methods" },
    { name: "boolean", description: "A data type that can only store true and false values" },
    { name: "break", description: "Breaks out of a loop or a switch block" },
    { name: "byte", description: "A data type that can store whole numbers from -128 to 127" },
    { name: "case", description: "Marks a block of code in switch statements" },
    { name: "catch", description: "Catches exceptions generated by try statements" },
    { name: "char", description: "A data type that is used to store a single character" },
    { name: "class", description: "Defines a class" },
    { name: "continue", description: "Continues to the next iteration of a loop" },
    { name: "default", description: "Specifies the default block of code in a switch statement" },
    { name: "do", description: "Used together with while to create a do-while loop" },
    { name: "double", description: "A data type that can store whole and fractional numbers" },
    { name: "else", description: "Used in conditional statements" },
    { name: "enum", description: "Declares an enumerated (unchangeable) type" },
    { name: "extends", description: "Extends a class (indicates that a class is inherited from another class)" },
    { name: "final", description: "A non-access modifier used for classes, attributes and methods" },
    { name: "finally", description: "Used with exceptions, a block of code that will be executed no matter if there is an exception or not" },
    { name: "float", description: "A data type that can store whole and fractional numbers" },
    { name: "for", description: "Create a for loop" },
    { name: "if", description: "Makes a conditional statement" },
    { name: "implements", description: "Implements an interface" },
    { name: "import", description: "Used to import a package, class or interface" },
    { name: "instanceof", description: "Checks whether an object is an instance of a specific class or an interface" },
    { name: "int", description: "A data type that can store whole numbers from -2147483648 to 2147483647" },
    { name: "interface", description: "Used to declare a special type of class that only contains abstract methods" },
    { name: "long", description: "A data type that can store whole numbers from -9223372036854775808 to 9223372036854775807" },
    { name: "new", description: "Creates new objects" },
    { name: "null", description: "Represents the absence of a value" },
    { name: "package", description: "Declares a package" },
    { name: "private", description: "An access modifier used for attributes, methods and constructors" },
    { name: "protected", description: "An access modifier used for attributes, methods and constructors" },
    { name: "public", description: "An access modifier used for classes, attributes, methods and constructors" },
    { name: "return", description: "Finished the execution of a method, and can be used to return a value from a method" },
    { name: "short", description: "A data type that can store whole numbers from -32768 to 32767" },
    { name: "static", description: "A non-access modifier used for methods and attributes" },
    { name: "super", description: "Refers to superclass (parent) objects" },
    { name: "switch", description: "Selects one of many code blocks to be executed" },
    { name: "this", description: "Refers to the current object in a method or constructor" },
    { name: "throw", description: "Creates a custom error" },
    { name: "throws", description: "Indicates what exceptions may be thrown by a method" },
    { name: "try", description: "Creates a try...catch statement" },
    { name: "void", description: "Specifies that a method should not have a return value" },
    { name: "while", description: "Creates a while loop" },
  ];

  return (
    <div className="min-h-screen bg-gray-50">
      <Header />
      
      <main className="max-w-7xl mx-auto px-4 py-12">
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            Java Reference
          </h1>
          <p className="text-lg text-gray-600">
            Complete reference of Java keywords and their descriptions
          </p>
        </div>

        <div className="bg-white rounded-lg shadow-md overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-green-600 text-white">
                <tr>
                  <th className="px-6 py-4 text-left font-semibold">Keyword</th>
                  <th className="px-6 py-4 text-left font-semibold">Description</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {keywords.map((keyword, index) => (
                  <tr
                    key={index}
                    className="hover:bg-gray-50 transition-colors"
                  >
                    <td className="px-6 py-4">
                      <code className="bg-gray-100 px-3 py-1 rounded font-mono text-sm font-semibold text-green-700">
                        {keyword.name}
                      </code>
                    </td>
                    <td className="px-6 py-4 text-gray-700">
                      {keyword.description}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <div className="mt-8 grid md:grid-cols-2 gap-6">
          <div className="bg-white p-6 rounded-lg shadow-md border border-gray-200">
            <h3 className="text-xl font-bold text-gray-900 mb-3">
              String Methods
            </h3>
            <p className="text-gray-600 mb-4">
              Explore commonly used String methods in Java
            </p>
            <ul className="space-y-2 text-sm">
              <li className="flex items-center gap-2">
                <code className="bg-gray-100 px-2 py-1 rounded text-green-700">length()</code>
                <span className="text-gray-600">- Returns the length of a string</span>
              </li>
              <li className="flex items-center gap-2">
                <code className="bg-gray-100 px-2 py-1 rounded text-green-700">toUpperCase()</code>
                <span className="text-gray-600">- Converts to uppercase</span>
              </li>
              <li className="flex items-center gap-2">
                <code className="bg-gray-100 px-2 py-1 rounded text-green-700">toLowerCase()</code>
                <span className="text-gray-600">- Converts to lowercase</span>
              </li>
              <li className="flex items-center gap-2">
                <code className="bg-gray-100 px-2 py-1 rounded text-green-700">indexOf()</code>
                <span className="text-gray-600">- Returns the index of a character</span>
              </li>
            </ul>
          </div>

          <div className="bg-white p-6 rounded-lg shadow-md border border-gray-200">
            <h3 className="text-xl font-bold text-gray-900 mb-3">
              Math Methods
            </h3>
            <p className="text-gray-600 mb-4">
              Explore commonly used Math methods in Java
            </p>
            <ul className="space-y-2 text-sm">
              <li className="flex items-center gap-2">
                <code className="bg-gray-100 px-2 py-1 rounded text-green-700">Math.max()</code>
                <span className="text-gray-600">- Returns the highest value</span>
              </li>
              <li className="flex items-center gap-2">
                <code className="bg-gray-100 px-2 py-1 rounded text-green-700">Math.min()</code>
                <span className="text-gray-600">- Returns the lowest value</span>
              </li>
              <li className="flex items-center gap-2">
                <code className="bg-gray-100 px-2 py-1 rounded text-green-700">Math.sqrt()</code>
                <span className="text-gray-600">- Returns the square root</span>
              </li>
              <li className="flex items-center gap-2">
                <code className="bg-gray-100 px-2 py-1 rounded text-green-700">Math.random()</code>
                <span className="text-gray-600">- Returns a random number</span>
              </li>
            </ul>
          </div>
        </div>
      </main>
    </div>
  );
}
